spring:
  datasource:
    # url: jdbc:mysql://localhost/figure_bed?serverTimezone=UTC
    url: jdbc:mysql://{数据库地址}/figure_bed?serverTimezone=UTC
    username: {用户}
    password: {密码}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
# 整合邮件配置
  mail:
    # smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    # 服务协议 smtp为发送邮件
    protocol: smtp
    
    #使用465邮件端口
    port: 465
    

    # 编码集
    default-encoding: UTF-8
    
    username: # 发送邮件的账户

    
    password: # 授权码 邮箱服务器提供的授权码，不是邮箱密码
    # 开启一些权限
    test-connection: true
    properties:
      mail:
        smtp:
          ssl: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: #redis地址
      client-type: lettuce
      lettuce:
        pool:
          max-active: 40
      jedis:
        pool:
          max-active: 40
      port: 6379

app:
  users:
    #用户数据存储位置 例如（必须以”/“结尾）：
    path: /root/java/figure-bed/usersource/
  virtual-mapping:
    #虚拟访问路径 例如
    dummy: /pic/**
    #本机实际物理地址（必须以”/“结尾）
    location: file:/root/java/figure-bed/usersource/
  ip-config:
    #你的ip或域名与虚拟路径的组合（必须以”/“结尾）关系到数据库的存储内容
    prefix: http://xxx.xxx.xxx.xxx:8080/pic/
